# Generated by Django 3.1.5 on 2021-01-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='btn_urls',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
